//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace visualSysWeb.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/nferecepcao2.asmx")]
        public string visualSysWeb_Nferecepcao2_NfeRecepcao2 {
            get {
                return ((string)(this["visualSysWeb_Nferecepcao2_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/nferetrecepcao2.asmx")]
        public string visualSysWeb_NfeRetRecepcao2_NfeRetRecepcao2 {
            get {
                return ((string)(this["visualSysWeb_NfeRetRecepcao2_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/nfeinutilizacao2.asmx")]
        public string visualSysWeb_NfeInutilizacao2_NfeInutilizacao2 {
            get {
                return ((string)(this["visualSysWeb_NfeInutilizacao2_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/nfeconsulta2.asmx")]
        public string visualSysWeb_NfeConsultaProtocolo_NfeConsulta2 {
            get {
                return ((string)(this["visualSysWeb_NfeConsultaProtocolo_NfeConsulta2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/nfestatusservico2.asmx")]
        public string visualSysWeb_NfeStatusServico2_NfeStatusServico2 {
            get {
                return ((string)(this["visualSysWeb_NfeStatusServico2_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/nfeweb/services/cadconsultacadastro2.asmx")]
        public string visualSysWeb_NfeConsultaCadastro_CadConsultaCadastro2 {
            get {
                return ((string)(this["visualSysWeb_NfeConsultaCadastro_CadConsultaCadastro2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/eventosWEB/services/RecepcaoEvento.asmx")]
        public string visualSysWeb_RecepcaoEvento_RecepcaoEvento {
            get {
                return ((string)(this["visualSysWeb_RecepcaoEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeRecepcao2.asmx")]
        public string visualSysWeb_HomologacaoNfeRecepcao2_NfeRecepcao2 {
            get {
                return ((string)(this["visualSysWeb_HomologacaoNfeRecepcao2_NfeRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/nfeweb/services/NfeRetRecepcao2.asmx")]
        public string visualSysWeb_HomologacaoNfeRetRecepcao2_NfeRetRecepcao2 {
            get {
                return ((string)(this["visualSysWeb_HomologacaoNfeRetRecepcao2_NfeRetRecepcao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeautorizacao.asmx")]
        public string visualSysWeb_Homologacao3NfeAutorizacao_NfeAutorizacao {
            get {
                return ((string)(this["visualSysWeb_Homologacao3NfeAutorizacao_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nferetautorizacao.asmx")]
        public string visualSysWeb_Homolocao3NFeRetAutorizacao_NfeRetAutorizacao {
            get {
                return ((string)(this["visualSysWeb_Homolocao3NFeRetAutorizacao_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/recepcaoevento.asmx")]
        public string visualSysWeb_Homologacao3RecepcaoEvento_RecepcaoEvento {
            get {
                return ((string)(this["visualSysWeb_Homologacao3RecepcaoEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/eventosWEB/services/RecepcaoEvento.asmx" +
            "")]
        public string visualSysWeb_HomologacaoRecepcaoEvento_RecepcaoEvento {
            get {
                return ((string)(this["visualSysWeb_HomologacaoRecepcaoEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/recepcaoevento.asmx")]
        public string visualSysWeb_Producao3RecepcaoEvento_RecepcaoEvento {
            get {
                return ((string)(this["visualSysWeb_Producao3RecepcaoEvento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/nfeautorizacao.asmx")]
        public string visualSysWeb_Producao3NfAutorizacao_NfeAutorizacao {
            get {
                return ((string)(this["visualSysWeb_Producao3NfAutorizacao_NfeAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/nferetautorizacao.asmx")]
        public string visualSysWeb_Producao3NfeRetAutorizacao_NfeRetAutorizacao {
            get {
                return ((string)(this["visualSysWeb_Producao3NfeRetAutorizacao_NfeRetAutorizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeinutilizacao2.asmx")]
        public string visualSysWeb_homologacao3NfeInutilizacao_NfeInutilizacao2 {
            get {
                return ((string)(this["visualSysWeb_homologacao3NfeInutilizacao_NfeInutilizacao2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/ws/nfeinutilizacao2.asmx")]
        public string visualSysWeb_Producao3NfeInutilizacao_NfeInutilizacao2 {
            get {
                return ((string)(this["visualSysWeb_Producao3NfeInutilizacao_NfeInutilizacao2"]));
            }
        }
    }
}
