using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using visualSysWeb.dao;
//using System.Threading.Tasks;

namespace XML_NFe
{
    class Item
    {
        public string ID = "";
        public int ide_nNF = 0;
        public string emit_cnpj = "";
        public string dest_cnpj = "";
        public DateTime ide_dEmi = Convert.ToDateTime("1900-01-01 00:00:00.000");
        public string det_prod_cProd = "";
        public string det_prod_cEAN = "";
        public string det_prod_xProd = "";
        public string det_prod_NCM = "";
        public string det_prod_EXTIPI = "";
        public int det_prod_genero = 0;
        public int det_prod_CFOP = 0;
        public string det_prod_uCOM = "";
        public decimal det_prod_qCOM = 0;
        public decimal det_prod_vUnCOM = 0;
        public decimal det_prod_vProd = 0;
        public string det_prod_cEANTrib = "";
        public string det_prod_uTrib = "";
        public decimal det_prod_qTrib = 0;
        public decimal det_prod_vUnTrib = 0;
        public decimal det_prod_vFrete = 0;
        public decimal det_prod_vSeg = 0;
        public decimal det_prod_vDesc = 0;
        public string det_prod_DI = "";
        public string det_prod_DetEspecifico = "";
        public decimal det_prod_vOutro = 0;
        public int det_prod_indTot = 0;
        public string det_prod_CEST = "";
        public int det_icms_orig = 0;
        public string det_icms_CST = "";
        public int det_icms_modBC = 0;
        public decimal det_icms_pRedBC = 0;
        public decimal det_icms_vBC = 0;
        public decimal det_icms_pICMS = 0;
        public decimal det_icms_vICMS = 0;
        public int det_icms_modBCST = 0;
        public decimal det_icms_pMVAST = 0;
        public decimal det_icms_pRedBCST = 0;
        public decimal det_icms_vBCST = 0;
        public decimal det_icms_pICMSST = 0;
        public decimal det_icms_vICMSST = 0;
        public int det_icms_CSOSN = 0;
        public decimal det_icms_pCredSN = 0;
        public decimal det_icms_vCredICMSSN = 0;
        public string det_ipi_clEnq = "";
        public string det_ipi_CNPJProd = "";
        public string det_ipi_cSelo = "";
        public decimal det_ipi_qSelo = 0;
        public string det_ipi_cEnq = "";
        public string det_ipi_CST = "";
        public decimal det_ipi_vBC = 0;
        public decimal det_ipi_pIPI = 0;
        public decimal det_ipi_vIPI = 0;
        public decimal det_ipi_qUnid = 0;
        public decimal det_ipi_vUnid = 0;
        public string det_pis_CST = "";
        public decimal det_pis_vBC = 0;
        public decimal det_pis_pPIS = 0;
        public decimal det_pis_vPIS = 0;
        public decimal det_pis_qBCProd = 0;
        public decimal det_pis_vAliqProd = 0;
        public string det_cofins_CST = "";
        public decimal det_cofins_vBC = 0;
        public decimal det_cofins_pCOFINS = 0;
        public decimal det_cofins_vCOFINS = 0;
        public decimal det_cofins_qBCProd = 0;
        public decimal det_cofins_vAliqProd = 0;
        public decimal det_icms_vBCFCPST = 0;
        public decimal det_icms_pFCPST = 0;
        public decimal det_icms_vFCPST = 0;
        public decimal det_icms_vBCFCP = 0;
        public decimal det_icms_pFCP = 0;
        public decimal det_icms_vFCP = 0;
        public int det_nItem = 0;

        public String Insert()
        {
            string sql = "INSERT INTO NFe_XML (";
            try
            {
                sql += "ID";
                sql += ", ide_nNF";
                sql += ", emit_cnpj";
                sql += ", dest_cnpj";
                sql += ", ide_dEmi";
                sql += ", det_nItem";
                sql += ", det_prod_cProd";
                sql += ", det_prod_cEAN";
                sql += ", det_prod_xProd";
                sql += ", det_prod_NCM";
                sql += ", det_prod_EXTIPI";
                sql += ", det_prod_genero";
                sql += ", det_prod_CFOP";
                sql += ", det_prod_uCOM";
                sql += ", det_prod_qCOM";
                sql += ", det_prod_vUnCOM";
                sql += ", det_prod_vProd";
                sql += ", det_prod_cEANTrib";
                sql += ", det_prod_uTrib";
                sql += ", det_prod_qTrib";
                sql += ", det_prod_vUnTrib";
                sql += ", det_prod_vFrete";
                sql += ", det_prod_vSeg";
                sql += ", det_prod_vDesc";
                sql += ", det_prod_DI";
                sql += ", det_prod_DetEspecifico";
                sql += ", det_prod_vOutro";
                sql += ", det_prod_indTot";
                sql += ", det_prod_CEST";
                sql += ", det_icms_orig";
                sql += ", det_icms_CST";
                sql += ", det_icms_modBC";
                sql += ", det_icms_pRedBC";
                sql += ", det_icms_vBC";
                sql += ", det_icms_pICMS";
                sql += ", det_icms_vICMS";
                sql += ", det_icms_modBCST";
                sql += ", det_icms_pMVAST";
                sql += ", det_icms_pRedBCST";
                sql += ", det_icms_vBCST";
                sql += ", det_icms_pICMSST";
                sql += ", det_icms_vICMSST";
                sql += ", det_icms_CSOSN";
                sql += ", det_icms_pCredSN";
                sql += ", det_icms_vCredICMSSN";
                sql += ", det_ipi_clEnq";
                sql += ", det_ipi_CNPJProd";
                sql += ", det_ipi_cSelo";
                sql += ", det_ipi_qSelo";
                sql += ", det_ipi_cEnq";
                sql += ", det_ipi_CST";
                sql += ", det_ipi_vBC";
                sql += ", det_ipi_pIPI";
                sql += ", det_ipi_vIPI";
                sql += ", det_ipi_qUnid";
                sql += ", det_ipi_vUnid";
                sql += ", det_pis_CST";
                sql += ", det_pis_vBC";
                sql += ", det_pis_pPIS";
                sql += ", det_pis_vPIS";
                sql += ", det_pis_qBCProd";
                sql += ", det_pis_vAliqProd";
                sql += ", det_cofins_CST";
                sql += ", det_cofins_vBC";
                sql += ", det_cofins_pCOFINS";
                sql += ", det_cofins_vCOFINS";
                sql += ", det_cofins_qBCProd";
                sql += ", det_cofins_vAliqProd";
                sql += ", det_icms_vBCFCPST";
                sql += ", det_icms_pFCPST";
                sql += ", det_icms_vFCPST";
                sql += ", det_icms_vBCFCP";
                sql += ", det_icms_pFCP";
                sql += ", det_icms_vFCP";
                sql += ") VALUES (";
                sql += "'" + this.ID + "'";
                sql += "," + this.ide_nNF.ToString().Replace(",", ".");
                sql += ",'" + this.emit_cnpj + "'";
                sql += ",'" + this.dest_cnpj + "'";
                sql += ",'" + this.ide_dEmi.ToString("yyyy-MM-dd HH:mm:ss") + "'";
                sql += "," + this.det_nItem.ToString();
                sql += ",'" + this.det_prod_cProd + "'";
                sql += ",'" + this.det_prod_cEAN + "'";
                sql += ",'" + this.det_prod_xProd + "'";
                sql += ",'" + this.det_prod_NCM + "'";
                sql += ",'" + this.det_prod_EXTIPI + "'";
                sql += "," + this.det_prod_genero.ToString().Replace(",", ".");
                sql += "," + this.det_prod_CFOP.ToString().Replace(",", ".");
                sql += ",'" + this.det_prod_uCOM + "'";
                sql += "," + this.det_prod_qCOM.ToString().Replace(",", ".");
                sql += "," + this.det_prod_vUnCOM.ToString().Replace(",", ".");
                sql += "," + this.det_prod_vProd.ToString().Replace(",", ".");
                sql += ",'" + this.det_prod_cEANTrib + "'";
                sql += ",'" + this.det_prod_uTrib + "'";
                sql += "," + this.det_prod_qTrib.ToString().Replace(",", ".");
                sql += "," + this.det_prod_vUnTrib.ToString().Replace(",", ".");
                sql += "," + this.det_prod_vFrete.ToString().Replace(",", ".");
                sql += "," + this.det_prod_vSeg.ToString().Replace(",", ".");
                sql += "," + this.det_prod_vDesc.ToString().Replace(",", ".");
                sql += ",'" + this.det_prod_DI + "'";
                sql += ",'" + this.det_prod_DetEspecifico + "'";
                sql += "," + this.det_prod_vOutro.ToString().Replace(",", ".");
                sql += "," + this.det_prod_indTot.ToString().Replace(",", ".");
                sql += ",'" + this.det_prod_CEST + "'";
                sql += "," + this.det_icms_orig.ToString().Replace(",", ".");
                sql += ",'" + this.det_icms_CST + "'";
                sql += "," + this.det_icms_modBC.ToString().Replace(",", ".");
                sql += "," + this.det_icms_pRedBC.ToString().Replace(",", ".");
                sql += "," + this.det_icms_vBC.ToString().Replace(",", ".");
                sql += "," + this.det_icms_pICMS.ToString().Replace(",", ".");
                sql += "," + this.det_icms_vICMS.ToString().Replace(",", ".");
                sql += "," + this.det_icms_modBCST.ToString().Replace(",", ".");
                sql += "," + this.det_icms_pMVAST.ToString().Replace(",", ".");
                sql += "," + this.det_icms_pRedBCST.ToString().Replace(",", ".");
                sql += "," + this.det_icms_vBCST.ToString().Replace(",", ".");
                sql += "," + this.det_icms_pICMSST.ToString().Replace(",", ".");
                sql += "," + this.det_icms_vICMSST.ToString().Replace(",", ".");
                sql += "," + this.det_icms_CSOSN.ToString().Replace(",", ".");
                sql += "," + this.det_icms_pCredSN.ToString().Replace(",", ".");
                sql += "," + this.det_icms_vCredICMSSN.ToString().Replace(",", ".");
                sql += ",'" + this.det_ipi_clEnq + "'";
                sql += ",'" + this.det_ipi_CNPJProd + "'";
                sql += ",'" + this.det_ipi_cSelo + "'";
                sql += "," + this.det_ipi_qSelo.ToString().Replace(",", ".");
                sql += ",'" + this.det_ipi_cEnq + "'";
                sql += ",'" + this.det_ipi_CST + "'";
                sql += "," + this.det_ipi_vBC.ToString().Replace(",", ".");
                sql += "," + this.det_ipi_pIPI.ToString().Replace(",", ".");
                sql += "," + this.det_ipi_vIPI.ToString().Replace(",", ".");
                sql += "," + this.det_ipi_qUnid.ToString().Replace(",", ".");
                sql += "," + this.det_ipi_vUnid.ToString().Replace(",", ".");
                sql += ",'" + this.det_pis_CST + "'";
                sql += "," + this.det_pis_vBC.ToString().Replace(",", ".");
                sql += "," + this.det_pis_pPIS.ToString().Replace(",", ".");
                sql += "," + this.det_pis_vPIS.ToString().Replace(",", ".");
                sql += "," + this.det_pis_qBCProd.ToString().Replace(",", ".");
                sql += "," + this.det_pis_vAliqProd.ToString().Replace(",", ".");
                sql += ",'" + this.det_cofins_CST + "'";
                sql += "," + this.det_cofins_vBC.ToString().Replace(",", ".");
                sql += "," + this.det_cofins_pCOFINS.ToString().Replace(",", ".");
                sql += "," + this.det_cofins_vCOFINS.ToString().Replace(",", ".");
                sql += "," + this.det_cofins_qBCProd.ToString().Replace(",", ".");
                sql += "," + this.det_cofins_vAliqProd.ToString().Replace(",", ".");
                sql += "," + this.det_icms_vBCFCPST.ToString().Replace(",", ".");
                sql += "," + this.det_icms_pFCPST.ToString().Replace(",", ".");
                sql += "," + this.det_icms_vFCPST.ToString().Replace(",", ".");
                sql += "," + this.det_icms_vBCFCP.ToString().Replace(",", ".");
                sql += "," + this.det_icms_pFCP.ToString().Replace(",", ".");
                sql += "," + this.det_icms_vFCP.ToString().Replace(",", ".");
                sql += "); ";
                return sql;
            }
            catch (Exception e)
            {
                //Program.GravarLog("Importador(Classe Item)", sql, e.Message.ToString());
                throw;
            }
        }
    }
}
