//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//
//     As alterações feitas neste arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace visualSysWeb.modulos.Estoque.pages
{


    public partial class FechamentoEstoqueDetalhes
    {
    }
}
