INSERT INTO PARAMETROS (PARAMETRO,VALOR_ATUAL,PERMITE_POR_EMPRESA,PENULT_ATUALIZACAO,ULT_ATUALIZACAO,GLOBAL,POR_USUARIO_OK ) 
		values ('NATUREZA_OP_PEDIDO_VENDA','5102',0,GETDATE(),GETDATE(),0,0)
GO
INSERT INTO PARAMETROS (PARAMETRO,VALOR_ATUAL,PERMITE_POR_EMPRESA,PENULT_ATUALIZACAO,ULT_ATUALIZACAO,GLOBAL,POR_USUARIO_OK ) 
		values ('NATUREZA_OP_PEDIDO_COMPRA','1101',0,GETDATE(),GETDATE(),0,0)
GO
INSERT INTO PARAMETROS (PARAMETRO,VALOR_ATUAL,PERMITE_POR_EMPRESA,PENULT_ATUALIZACAO,ULT_ATUALIZACAO,GLOBAL,POR_USUARIO_OK ) 
		values ('TABELA_DESCONTO_VENDA','NORMAL',0,GETDATE(),GETDATE(),0,0)
GO

