GO

/****** Object:  Table [dbo].[Acumulado_Geral]    Script Date: 04/07/2015 10:40:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Acumulado_Geral](
	[FILIAL] [varchar](20) NOT NULL,
	[PLU] [varchar](20) NOT NULL,
	[EAN] [varchar](17) NULL,
	[DESCRICAO] [varchar](60) NULL,
	[GRUPO] [int] NULL,
	[GRUPO_DESCRICAO] [varchar](40) NULL,
	[SUBGRUPO] [varchar](6) NULL,
	[SUBGRUPO_DESCRICAO] [varchar](40) NULL,
	[DEPARTAMENTO] [varchar](9) NULL,
	[DEPARTAMENTO_DESCRICAO] [varchar](40) NULL,
	[CST_ICMS] [varchar](2) NULL,
	[ALIQUOTA_ICMS] [numeric](6, 2) NULL,
	[CST_PISCOFINS_ENTRADA] [varchar](2) NULL,
	[CST_PISCOFINS_SAIDA] [varchar](2) NULL,
	[ALIQUOTA_PIS] [numeric](6, 2) NULL,
	[ALIQUOTA_COFINS] [numeric](6, 2) NULL,
	[PRECO_CUSTO] [numeric](12, 2) NULL,
	[PRECO_VENDA] [numeric](12, 2) NULL,
	[SALDO_ATUAL] [numeric](14, 3) NULL,
	[PEDIDO_PENDENETE] [numeric](14, 3) NULL,
	[CUSTOMES13] [numeric](14, 3) NULL,
	[CUSTOMES12] [numeric](14, 3) NULL,
	[CUSTOMES11] [numeric](14, 3) NULL,
	[CUSTOMES10] [numeric](14, 3) NULL,
	[CUSTOMES09] [numeric](14, 3) NULL,
	[CUSTOMES08] [numeric](14, 3) NULL,
	[CUSTOMES07] [numeric](14, 3) NULL,
	[CUSTOMES06] [numeric](14, 3) NULL,
	[CUSTOMES05] [numeric](14, 3) NULL,
	[CUSTOMES04] [numeric](14, 3) NULL,
	[CUSTOMES03] [numeric](14, 3) NULL,
	[CUSTOMES02] [numeric](14, 3) NULL,
	[CUSTOMES01] [numeric](14, 3) NULL,
	[VQMES13] [numeric](14, 3) NULL,
	[VQMES12] [numeric](14, 3) NULL,
	[VQMES11] [numeric](14, 3) NULL,
	[VQMES10] [numeric](14, 3) NULL,
	[VQMES09] [numeric](14, 3) NULL,
	[VQMES08] [numeric](14, 3) NULL,
	[VQMES07] [numeric](14, 3) NULL,
	[VQMES06] [numeric](14, 3) NULL,
	[VQMES05] [numeric](14, 3) NULL,
	[VQMES04] [numeric](14, 3) NULL,
	[VQMES03] [numeric](14, 3) NULL,
	[VQMES02] [numeric](14, 3) NULL,
	[VQMES01] [numeric](14, 3) NULL,
	[VVMES13] [numeric](14, 2) NULL,
	[VVMES12] [numeric](14, 2) NULL,
	[VVMES11] [numeric](14, 2) NULL,
	[VVMES10] [numeric](14, 2) NULL,
	[VVMES09] [numeric](14, 2) NULL,
	[VVMES08] [numeric](14, 2) NULL,
	[VVMES07] [numeric](14, 2) NULL,
	[VVMES06] [numeric](14, 2) NULL,
	[VVMES05] [numeric](14, 2) NULL,
	[VVMES04] [numeric](14, 2) NULL,
	[VVMES03] [numeric](14, 2) NULL,
	[VVMES02] [numeric](14, 2) NULL,
	[VVMES01] [numeric](14, 2) NULL,
	[EQMES13] [numeric](14, 3) NULL,
	[EQMES12] [numeric](14, 3) NULL,
	[EQMES11] [numeric](14, 3) NULL,
	[EQMES10] [numeric](14, 3) NULL,
	[EQMES09] [numeric](14, 3) NULL,
	[EQMES08] [numeric](14, 3) NULL,
	[EQMES07] [numeric](14, 3) NULL,
	[EQMES06] [numeric](14, 3) NULL,
	[EQMES05] [numeric](14, 3) NULL,
	[EQMES04] [numeric](14, 3) NULL,
	[EQMES03] [numeric](14, 3) NULL,
	[EQMES02] [numeric](14, 3) NULL,
	[EQMES01] [numeric](14, 3) NULL,
	[EVMES13] [numeric](14, 2) NULL,
	[EVMES12] [numeric](14, 2) NULL,
	[EVMES11] [numeric](14, 2) NULL,
	[EVMES10] [numeric](14, 2) NULL,
	[EVMES09] [numeric](14, 2) NULL,
	[EVMES08] [numeric](14, 2) NULL,
	[EVMES07] [numeric](14, 2) NULL,
	[EVMES06] [numeric](14, 2) NULL,
	[EVMES05] [numeric](14, 2) NULL,
	[EVMES04] [numeric](14, 2) NULL,
	[EVMES03] [numeric](14, 2) NULL,
	[EVMES02] [numeric](14, 2) NULL,
	[EVMES01] [numeric](14, 2) NULL,
	[FLAG] [char](1) NULL,
	[INICIO] [date] NULL,
	[FIM] [date] NULL,
 CONSTRAINT [PK_Acumulado_Geral] PRIMARY KEY CLUSTERED 
(
	[FILIAL] ASC,
	[PLU] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF_Acumulado_Geral_SALDO_ATUAL]  DEFAULT ((0)) FOR [SALDO_ATUAL]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VQMES__1AC31988]  DEFAULT ((0)) FOR [VQMES13]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VQMES__1BB73DC1]  DEFAULT ((0)) FOR [VQMES12]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VQMES__1CAB61FA]  DEFAULT ((0)) FOR [VQMES11]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VQMES__1D9F8633]  DEFAULT ((0)) FOR [VQMES10]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VQMES__1E93AA6C]  DEFAULT ((0)) FOR [VQMES09]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VQMES__1F87CEA5]  DEFAULT ((0)) FOR [VQMES08]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VQMES__207BF2DE]  DEFAULT ((0)) FOR [VQMES07]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VQMES__21701717]  DEFAULT ((0)) FOR [VQMES06]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VQMES__22643B50]  DEFAULT ((0)) FOR [VQMES05]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VQMES__23585F89]  DEFAULT ((0)) FOR [VQMES04]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VQMES__244C83C2]  DEFAULT ((0)) FOR [VQMES03]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VQMES__2540A7FB]  DEFAULT ((0)) FOR [VQMES02]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VQMES__2634CC34]  DEFAULT ((0)) FOR [VQMES01]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VVMES__2728F06D]  DEFAULT ((0)) FOR [VVMES13]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VVMES__281D14A6]  DEFAULT ((0)) FOR [VVMES12]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VVMES__291138DF]  DEFAULT ((0)) FOR [VVMES11]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VVMES__2A055D18]  DEFAULT ((0)) FOR [VVMES10]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VVMES__2AF98151]  DEFAULT ((0)) FOR [VVMES09]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VVMES__2BEDA58A]  DEFAULT ((0)) FOR [VVMES08]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VVMES__2CE1C9C3]  DEFAULT ((0)) FOR [VVMES07]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VVMES__2DD5EDFC]  DEFAULT ((0)) FOR [VVMES06]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VVMES__2ECA1235]  DEFAULT ((0)) FOR [VVMES05]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VVMES__2FBE366E]  DEFAULT ((0)) FOR [VVMES04]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VVMES__30B25AA7]  DEFAULT ((0)) FOR [VVMES03]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VVMES__31A67EE0]  DEFAULT ((0)) FOR [VVMES02]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__VVMES__329AA319]  DEFAULT ((0)) FOR [VVMES01]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EQMES__338EC752]  DEFAULT ((0)) FOR [EQMES13]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EQMES__3482EB8B]  DEFAULT ((0)) FOR [EQMES12]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EQMES__35770FC4]  DEFAULT ((0)) FOR [EQMES11]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EQMES__366B33FD]  DEFAULT ((0)) FOR [EQMES10]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EQMES__375F5836]  DEFAULT ((0)) FOR [EQMES09]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EQMES__38537C6F]  DEFAULT ((0)) FOR [EQMES08]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EQMES__3947A0A8]  DEFAULT ((0)) FOR [EQMES07]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EQMES__3A3BC4E1]  DEFAULT ((0)) FOR [EQMES06]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EQMES__3B2FE91A]  DEFAULT ((0)) FOR [EQMES05]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EQMES__3C240D53]  DEFAULT ((0)) FOR [EQMES04]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EQMES__3D18318C]  DEFAULT ((0)) FOR [EQMES03]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EQMES__3E0C55C5]  DEFAULT ((0)) FOR [EQMES02]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EQMES__3F0079FE]  DEFAULT ((0)) FOR [EQMES01]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EVMES__3FF49E37]  DEFAULT ((0)) FOR [EVMES13]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EVMES__40E8C270]  DEFAULT ((0)) FOR [EVMES12]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EVMES__41DCE6A9]  DEFAULT ((0)) FOR [EVMES11]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EVMES__42D10AE2]  DEFAULT ((0)) FOR [EVMES10]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EVMES__43C52F1B]  DEFAULT ((0)) FOR [EVMES09]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EVMES__44B95354]  DEFAULT ((0)) FOR [EVMES08]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EVMES__45AD778D]  DEFAULT ((0)) FOR [EVMES07]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EVMES__46A19BC6]  DEFAULT ((0)) FOR [EVMES06]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EVMES__4795BFFF]  DEFAULT ((0)) FOR [EVMES05]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EVMES__4889E438]  DEFAULT ((0)) FOR [EVMES04]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EVMES__497E0871]  DEFAULT ((0)) FOR [EVMES03]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EVMES__4A722CAA]  DEFAULT ((0)) FOR [EVMES02]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF__Acumulado__EVMES__4B6650E3]  DEFAULT ((0)) FOR [EVMES01]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF_Acumulado_Geral_FLAG]  DEFAULT ('') FOR [FLAG]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF_Acumulado_Geral_INICIO]  DEFAULT ('') FOR [INICIO]
GO

ALTER TABLE [dbo].[Acumulado_Geral] ADD  CONSTRAINT [DF_Acumulado_Geral_FIM]  DEFAULT ('') FOR [FIM]
GO


/****** Object:  StoredProcedure [dbo].[sp_br_Mercadoria_Acum]    Script Date: 04/07/2015 10:39:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


--=============================
--sp_br_mercadoria_Acum '10057', 'matriz'
ALTER    PROCEDURE [dbo].[sp_br_Mercadoria_Acum] 
	@PLU Char(6), @Filial varchar(20) output
AS

begin
	declare @contador as integer

declare @data as datetime

 

set @contador = -12

set @data = dateadd(month, @contador,getdate())

 

create table #lixo (dataref datetime)

 

while @contador <= 0

      begin

            insert into #lixo select dateadd(month, @contador, getdate())

            set @contador = @contador + 1
      end

	select MesAno = substring(convert(varchar,lixo.dataref,102),1,7),
qtde = sum(ISNULL(SAI.Qtde,0)), vlr = sum(ISNULL(SAI.vlr,0)), PrcMD =
convert(decimal(9,2),avg(case when isnull(SAI.Vlr,0) > 0 and
isnull(SAI.Qtde,0) > 0 then isnull(SAI.Vlr,0)/isnull(SAI.Qtde,0) else 0
end))
	From #lixo lixo left join saida_Estoque Sai (index
=IX_saida_estoque_01 ) on substring(convert(varchar,lixo.dataref,102),1,7)=
substring(convert(varchar,sai.data_movimento,102),1,7)AND SAI.PLU=@PLU AND
Filial=@Filial
	group by substring(convert(varchar,lixo.dataref,102),1,7)
	
	order by 1 desc
	
	end




GO
GO

/****** Object:  StoredProcedure [dbo].[sp_br_Mercadoria_Acum_Dia]    Script Date: 04/07/2015 10:40:12 ******/
SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER OFF
GO





-- sp_br_mercadoria_acum_dia '10057', 'matriz'
ALTER     PROCEDURE [dbo].[sp_br_Mercadoria_Acum_Dia] 
	@PLU Char(6), @Filial varchar(20) output
AS
	begin
		select 
		Dia = case 
			when datepart(weekday, saida_estoque.data_movimento)
= 1 then 'Dom'
			when datepart(weekday, saida_estoque.data_movimento)
= 2 then 'Seg'
			when datepart(weekday, saida_estoque.data_movimento)
= 3 then 'Ter'
			when datepart(weekday, saida_estoque.data_movimento)
= 4 then 'Qua'
			when datepart(weekday, saida_estoque.data_movimento)
= 5 then 'Qui'
			when datepart(weekday, saida_estoque.data_movimento)
= 6 then 'Sex'
			else 'Sab' end + '-' + substring(convert(varchar,
Data_Movimento, 101), 1, 5),
		--data_movimento, 
		qtde = sum(qtde), vlr = sum(vlr), PrcMD =
convert(decimal(9,2),avg(case when isnull(saida_estoque.Vlr,0) > 0 and
isnull(saida_estoque.Qtde,0) > 0 then
isnull(saida_estoque.Vlr,0)/isnull(saida_estoque.Qtde,0) else 0 end))
		from saida_Estoque (index=ix_saida_estoque_01) inner join
mercadoria on saida_Estoque.plu = mercadoria.plu where 
		saida_estoque.Filial = @Filial
		and saida_Estoque.plu = @PLU
		and data_movimento >= dateadd(Day,-15,GetDate())
		group by data_movimento, saida_estoque.plu, descricao
		order by data_movimento Desc
	end




GO
GO

/****** Object:  StoredProcedure [dbo].[sp_br_Rel_Geral_Acum]    Script Date: 04/07/2015 10:40:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


--=============================

--sp_br_Rel_Geral_Acum 'matriz', '', ''
CREATE    PROCEDURE [dbo].[sp_br_Rel_Geral_Acum] 
	@Filial			varchar(20), 
	@Descricao		Varchar(60) = '',
	@Departamento	Varchar(40) = '' output
AS

begin
	declare @contador as integer
	declare @data as datetime
	Declare @String               As nVarchar(2000)

	set @contador = -12
	set @data = dateadd(month, @contador,getdate())

	create table #lixo (dataref datetime)

	WHILE @contador <= 0

	  BEGIN
			insert into #lixo select dateadd(month, @contador, getdate())

			set @contador = @contador + 1
	  END

	SET @String = 'select merc.plu, merc.descricao, merc.codigo_departamento, merc.descricao_departamento, MesAno = SUBSTRING(CONVERT(VARCHAR,lixo.dataref,102),1,7), qtde = SUM(ISNULL(SAI.Qtde,0)), vlr = SUM(ISNULL(SAI.vlr,0)), '
	SET @String = @String + 'PrcMD = CONVERT(DECIMAL(9,2),AVG(CASE WHEN ISNULL(SAI.Vlr,0) > 0 and ISNULL(SAI.Qtde,0) > 0 THEN ISNULL(SAI.Vlr,0)/isnull(SAI.Qtde,0) else 0 end)) '
	SET @String = @String + ' into #Geral_Acum'
	SET @String = @String + ' From #lixo lixo LEFT JOIN saida_Estoque Sai (INDEX =IX_saida_estoque) ON SUBSTRING(CONVERT(VARCHAR,lixo.dataref,102),1,7)= substring(convert(varchar,sai.data_movimento,102),1,7)AND Filial= ' + CHAR(39) + @Filial + CHAR(39)
	SET @String = @String + ' INNER JOIN mercadoria Merc on Sai.PLU = Merc.PLU WHERE LEN(Merc.PLU) > 0'
	
	BEGIN
		IF LEN(ISNULL(@Descricao,'')) >0
			SET @String = @String + ' AND Merc.Descricao LIKE ' + CHAR(39) + '%' + @Descricao + '%' + CHAR(39) 

		IF LEN(ISNULL(@Departamento,'')) >0
			BEGIN
				SET @String = @String + ' AND EXISTS(select * from departamento where merc.codigo_departamento = departamento.codigo_departamento '
				SET @String = @String + ' AND departamento.descricao_departamento LIKE ' + CHAR(39) + '%' + @Departamento + '%' + CHAR(39) + ')'
			END
	
	END
			
	SET @String = @String + ' GROUP BY SUBSTRING(CONVERT(VARCHAR,lixo.dataref,102),1,7), merc.plu, merc.descricao, merc.codigo_departamento, merc.descricao_departamento'
	SET @String = @String + ' ORDER BY 1 DESC'
	
	SET @String = @String + ' SELECT TOP 30 PLU, DESCRICAO, CODIGO_DEPARTAMENTO, DESCRICAO_DEPARTAMENTO, '
	SET @String = @String + ' SUM(QTDE) AS Qtde, SUM(VLR) As Vlr, AVG(VLR/QTDE) As PRcMD FROM #Geral_Acum '
	SET @String = @String + ' GROUP BY PLU, DESCRICAO, CODIGO_DEPARTAMENTO, DESCRICAO_DEPARTAMENTO ORDER BY 6 DESC'
	--print @String
	EXECUTE(@String)
	
END


GO



/****** Object:  StoredProcedure [dbo].[sp_br_Acumulado_Geral]    Script Date: 04/07/2015 11:13:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- Batch submitted through debugger: SQLQuery1.sql|7|0|C:\Users\Jailson\AppData\Local\Temp\~vsD9F4.sql
CREATE PROCEDURE [dbo].[sp_br_Acumulado_Geral]

AS
	DECLARE @FILIAL VARCHAR(20)
	DECLARE @PLU	VARCHAR(17)
	
	DELETE FROM 
		Acumulado_Geral
		
	BEGIN
		INSERT INTO 
			Acumulado_Geral
		SELECT
			FILIAL = ML.FILIAL,
			PLU = M.PLU,
			EAN = ISNULL((SELECT MAX(EAN.EAN) FROM EAN WHERE EAN.PLU = M.PLU),''),
			DESCRICAO = M.DESCRICAO,
			GRUPO = CONVERT(INT, SUBSTRING(M.CODIGO_DEPARTAMENTO, 1, 3)),
			GRUPO_DESCRICAO = ISNULL((SELECT DESCRICAO_GRUPO FROM GRUPO WHERE GRUPO.CODIGO_GRUPO = CONVERT(INT, SUBSTRING(M.CODIGO_DEPARTAMENTO,1,3))),''),
			SUBGRUPO = SUBSTRING(M.CODIGO_DEPARTAMENTO, 1, 6),
			SUBGRUPO_DESCRICAO = ISNULL((SELECT DESCRICAO_SUBGRUPO FROM SUBGRUPO WHERE SUBGRUPO.CODIGO_SUBGRUPO = SUBSTRING(M.CODIGO_DEPARTAMENTO,1,6)),''),
			DEPARTAMENTO = M.CODIGO_DEPARTAMENTO,
			DEPARTAMENTO_DESCRICAO = ISNULL((SELECT DESCRICAO_DEPARTAMENTO FROM DEPARTAMENTO WHERE DEPARTAMENTO.CODIGO_DEPARTAMENTO = M.CODIGO_DEPARTAMENTO),''),
			CST_ICMS = ISNULL(M.ORIGEM,'0') + ISNULL(T.INDICE_ST,'00'),
			ALIQUOTA_ICMS = ISNULL(T.ICMS_EFETIVO, 0),
			CST_PISCOFINS_ENTRADA = ISNULL(M.CST_ENTRADA, '50'),
			CST_PISCOFINS_SAIDA = ISNULL(M.CST_SAIDA, '01'),
			ALIQUOTA_PIS = CASE WHEN CONVERT(INT, ISNULL(M.CST_ENTRADA, 50)) BETWEEN 50 AND 66 THEN FILIAL.PIS ELSE 0 END, 
			ALIQUOTA_COFINS = CASE WHEN CONVERT(INT, ISNULL(M.CST_ENTRADA, 50)) BETWEEN 50 AND 66 THEN FILIAL.COFINS ELSE 0 END,
			PRECO_CUSTO = ML.PRECO_CUSTO,
			PRECO_VENDA = ML.PRECO,
			SALDO_ATUAL = ML.SALDO_ATUAL,
			PEDIDO_PENDENTE = 0,
			CUSTOMES13 = ML.PRECO_CUSTO,
			CUSTOMES12 = ML.PRECO_CUSTO,
			CUSTOMES11 = ML.PRECO_CUSTO,
			CUSTOMES10 = ML.PRECO_CUSTO,
			CUSTOMES09 = ML.PRECO_CUSTO,
			CUSTOMES08 = ML.PRECO_CUSTO,
			CUSTOMES07 = ML.PRECO_CUSTO,
			CUSTOMES06 = ML.PRECO_CUSTO,
			CUSTOMES05 = ML.PRECO_CUSTO,
			CUSTOMES04 = ML.PRECO_CUSTO,
			CUSTOMES03 = ML.PRECO_CUSTO,
			CUSTOMES02 = ML.PRECO_CUSTO,
			CUSTOMES01 = ML.PRECO_CUSTO,
			VQMES13 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -12, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VQMES12 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -11, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VQMES11 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -10, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VQMES10 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -9, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VQMES09 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -8, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VQMES08 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -7, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VQMES07 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -6, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VQMES06 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -5, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VQMES05 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -4, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VQMES04 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -3, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VQMES03 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -2, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VQMES02 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -1, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VQMES01 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, 0, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VVMES13 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -12, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VVMES12 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -11, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VVMES11 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -10, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VVMES10 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -9, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VVMES09 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -8, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VVMES08 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -7, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VVMES07 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -6, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VVMES06 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -5, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VVMES05 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -4, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VVMES04 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -3, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VVMES03 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -2, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VVMES02 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -1, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			VVMES01 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, 0, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),
			EQMES13 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -12, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EQMES12 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -11, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EQMES11 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -10, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EQMES10 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -9, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EQMES09 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -8, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EQMES08 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -7, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EQMES07 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -6, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EQMES06 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -5, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EQMES05 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -4, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EQMES04 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -3, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EQMES03 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -2, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EQMES02 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -1, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EQMES01 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, 0, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EVMES13 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -12, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EVMES12 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -11, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EVMES11 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -10, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EVMES10 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -9, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EVMES09 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -8, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EVMES08 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -7, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EVMES07 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -6, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EVMES06 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -5, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EVMES05 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -4, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EVMES04 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -3, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EVMES03 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -2, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EVMES02 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -1, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			EVMES01 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, 0, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),
			FLAG = '',
			INICIO = '1900-01-01',
			FIM = '1900-01-01'
		FROM 
			MERCADORIA M 
			INNER JOIN MERCADORIA_LOJA ML ON M.PLU = ML.PLU 
			INNER JOIN FILIAL ON FILIAL.FILIAL = ML.FILIAL
			LEFT OUTER JOIN TRIBUTACAO T ON M.CODIGO_TRIBUTACAO = T.CODIGO_TRIBUTACAO
	END
	/*
	BEGIN
		-- SELECIONA APENAS OS PRODUTOS QUE TIVERAM ENTRADAS
		-- NOS ULTIMOS 13 MESES
		SELECT DISTINCT NF.FILIAL, NF_ITEM.PLU INTO #PLUENTRADA FROM NF INNER JOIN NF_ITEM ON NF.FILIAL = NF_ITEM.FILIAL AND NF.CLIENTE_FORNECEDOR = NF_ITEM.CLIENTE_FORNECEDOR AND NF.CODIGO = NF_ITEM.CODIGO 
		WHERE SUBSTRING(CONVERT(VARCHAR, NF.DATA), 1, 7) >= SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -12, GETDATE()), 102), 1, 7)
		
		IF (SELECT COUNT(*) FROM #PLUENTRADA) > 0
		BEGIN

			UPDATE Acumulado_Geral SET INICIO = GETDATE()
			
			DECLARE curEntPLU CURSOR 
				FOR SELECT * FROM #PLUENTRADA 

			OPEN curEntPLU
			
			FETCH NEXT FROM curEntPLU into @FILIAL, @PLU
			
			WHILE @@fetch_status = 0
				BEGIN
					UPDATE Acumulado_Geral SET
						CUSTOMES13 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -12, GETDATE()), 102), 1, 7)), PRECO_CUSTO),
						CUSTOMES12 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -11, GETDATE()), 102), 1, 7)), PRECO_CUSTO),
						CUSTOMES11 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -10, GETDATE()), 102), 1, 7)), PRECO_CUSTO),
						CUSTOMES10 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -9, GETDATE()), 102), 1, 7)), PRECO_CUSTO),
						CUSTOMES09 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -8, GETDATE()), 102), 1, 7)), PRECO_CUSTO),
						CUSTOMES08 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -7, GETDATE()), 102), 1, 7)), PRECO_CUSTO),
						CUSTOMES07 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -6, GETDATE()), 102), 1, 7)), PRECO_CUSTO),
						CUSTOMES06 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -5, GETDATE()), 102), 1, 7)), PRECO_CUSTO),
						CUSTOMES05 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -4, GETDATE()), 102), 1, 7)), PRECO_CUSTO),
						CUSTOMES04 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -3, GETDATE()), 102), 1, 7)), PRECO_CUSTO),
						CUSTOMES03 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -2, GETDATE()), 102), 1, 7)), PRECO_CUSTO),
						CUSTOMES02 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -1, GETDATE()), 102), 1, 7)), PRECO_CUSTO),
						CUSTOMES01 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, 0, GETDATE()), 102), 1, 7)), PRECO_CUSTO),
						FLAG ='*'
					WHERE
						Acumulado_Geral.FILIAL = @FILIAL
					AND
						Acumulado_Geral.PLU = @PLU
						
					FETCH NEXT FROM curEntPLU into @FILIAL, @PLU
				END
				CLOSE curEntPLU
				DEALLOCATE curEntPLUxPlu
		END
		UPDATE Acumulado_Geral SET FIM = GETDATE()
	END
	*/
--	WHERE M.PLU = '1656'

GO





/****** Object:  Index [IX_NF_01]    Script Date: 04/07/2015 11:19:49 ******/
CREATE NONCLUSTERED INDEX [IX_NF_01] ON [dbo].[NF] 
(
	[Filial] ASC,
	[Data] ASC,
	[Cliente_Fornecedor] ASC,
	[Codigo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

GO

/****** Object:  Index [IX_NF_ITEM_01]    Script Date: 04/07/2015 11:20:29 ******/
CREATE NONCLUSTERED INDEX [IX_NF_ITEM_01] ON [dbo].[NF_Item] 
(
	[Filial] ASC,
	[Cliente_Fornecedor] ASC,
	[Codigo] ASC,
	[PLU] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

GO

/****** Object:  Index [IX_NF_ITEM_02]    Script Date: 04/07/2015 11:20:50 ******/
CREATE NONCLUSTERED INDEX [IX_NF_ITEM_02] ON [dbo].[NF_Item] 
(
	[Filial] ASC,
	[PLU] ASC,
	[Cliente_Fornecedor] ASC,
	[Codigo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO





