INSERT INTO PARAMETROS (PARAMETRO,VALOR_ATUAL,PERMITE_POR_EMPRESA,PENULT_ATUALIZACAO,ULT_ATUALIZACAO,GLOBAL,POR_USUARIO_OK ) 
		values ('CENTRO_CUSTO_PEDIDO_VENDA','013001001',0,GETDATE(),GETDATE(),0,0)
