
insert into PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,ULT_ATUALIZACAO,VALOR_ATUAL,POR_USUARIO_OK,PERMITE_POR_EMPRESA,GLOBAL,DESC_PARAMETRO)
			     values ('BAIXA_ESTOQUE_PED_VENDA',GETDATE() ,GETDATE() ,'FALSE',0,0,0,'BAIXA ESTOQUE NO PEDIDO DE VENDA')

insert into PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,ULT_ATUALIZACAO,VALOR_ATUAL,POR_USUARIO_OK,PERMITE_POR_EMPRESA,GLOBAL,DESC_PARAMETRO)
			     values ('PEDIDO_VDA_VEND_OBRIG',GETDATE() ,GETDATE() ,'FALSE',0,0,0,'PEDIDO DE VENDA OBRIGATORIO INFORMAR VENDEDOR')

insert into PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,ULT_ATUALIZACAO,VALOR_ATUAL,POR_USUARIO_OK,PERMITE_POR_EMPRESA,GLOBAL,DESC_PARAMETRO)
			     values ('PEDIDOS_NAOLISTAR_GRID',GETDATE() ,GETDATE() ,'FALSE',0,0,0,'NÃO APRESENTAR PEDIDOS NA GRID')
insert into PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,ULT_ATUALIZACAO,VALOR_ATUAL,POR_USUARIO_OK,PERMITE_POR_EMPRESA,GLOBAL,DESC_PARAMETRO)
			     values ('INIBE_CUSTO_PRODUTO',GETDATE() ,GETDATE() ,'FALSE',0,0,0,'NÃO APRESENTAR O CUSTO DA MERCADORIA NA GRID DO CADSTRO')
insert into PARAMETROS (PARAMETRO,PENULT_ATUALIZACAO,ULT_ATUALIZACAO,VALOR_ATUAL,POR_USUARIO_OK,PERMITE_POR_EMPRESA,GLOBAL,DESC_PARAMETRO)
			     values ('PEDIDO_SOCOMESTOQUE',GETDATE() ,GETDATE() ,'FALSE',0,0,0,'PEDIDO SO COM ESTOQUE')

