IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[sp_br_Acumulado_Geral]') AND type in (N'P', N'PC'))
begin 
DROP PROCEDURE [dbo].[sp_br_Acumulado_Geral]
end 

go

create  PROCEDURE [dbo].[sp_br_Acumulado_Geral]

 

AS

                DECLARE @FILIAL VARCHAR(20)

                DECLARE @PLU VARCHAR(17)

 

                DELETE FROM

                               Acumulado_Geral

 

                BEGIN

                               INSERT INTO

                                               Acumulado_Geral

                               SELECT

                                               FILIAL = ML.FILIAL,

                                               PLU = M.PLU,

                                               EAN = ISNULL((SELECT MAX(EAN.EAN) FROM EAN WHERE EAN.PLU = M.PLU),''),

                                               DESCRICAO = M.DESCRICAO,

                                               GRUPO = CONVERT(INT, SUBSTRING(M.CODIGO_DEPARTAMENTO, 1, 3)),

                                               GRUPO_DESCRICAO = ISNULL((SELECT DESCRICAO_GRUPO FROM GRUPO WHERE GRUPO.CODIGO_GRUPO = CONVERT(INT, SUBSTRING(M.CODIGO_DEPARTAMENTO,1,3))),''),

                                               SUBGRUPO = SUBSTRING(M.CODIGO_DEPARTAMENTO, 1, 6),

                                               SUBGRUPO_DESCRICAO = ISNULL((SELECT DESCRICAO_SUBGRUPO FROM SUBGRUPO WHERE SUBGRUPO.CODIGO_SUBGRUPO = SUBSTRING(M.CODIGO_DEPARTAMENTO,1,6)),''),

                                               DEPARTAMENTO = M.CODIGO_DEPARTAMENTO,

                                               DEPARTAMENTO_DESCRICAO = ISNULL((SELECT DESCRICAO_DEPARTAMENTO FROM DEPARTAMENTO WHERE DEPARTAMENTO.CODIGO_DEPARTAMENTO = M.CODIGO_DEPARTAMENTO),''),

                                               CST_ICMS = ISNULL(M.ORIGEM,'0') + ISNULL(T.INDICE_ST,'00'),

                                               ALIQUOTA_ICMS = ISNULL(T.ICMS_EFETIVO, 0),

                                               CST_PISCOFINS_ENTRADA = ISNULL(M.CST_ENTRADA, '50'),

                                               CST_PISCOFINS_SAIDA = ISNULL(M.CST_SAIDA, '01'),

                                               ALIQUOTA_PIS = CASE WHEN CONVERT(INT, ISNULL(M.CST_ENTRADA, 50)) BETWEEN 50 AND 66 THEN FILIAL.PIS ELSE 0 END,

                                               ALIQUOTA_COFINS = CASE WHEN CONVERT(INT, ISNULL(M.CST_ENTRADA, 50)) BETWEEN 50 AND 66 THEN FILIAL.COFINS ELSE 0 END,

                                               PRECO_CUSTO = ML.PRECO_CUSTO,

                                               PRECO_VENDA = ML.PRECO,

                                               SALDO_ATUAL = ML.SALDO_ATUAL,

                                               PEDIDO_PENDENTE = 0,

                                                CUSTOMES13 = ML.PRECO_CUSTO,

                                               CUSTOMES12 = ML.PRECO_CUSTO,

                                               CUSTOMES11 = ML.PRECO_CUSTO,

                                               CUSTOMES10 = ML.PRECO_CUSTO,

                                               CUSTOMES09 = ML.PRECO_CUSTO,

                                               CUSTOMES08 = ML.PRECO_CUSTO,

                                               CUSTOMES07 = ML.PRECO_CUSTO,

                                               CUSTOMES06 = ML.PRECO_CUSTO,

                                                CUSTOMES05 = ML.PRECO_CUSTO,

                                               CUSTOMES04 = ML.PRECO_CUSTO,

                                               CUSTOMES03 = ML.PRECO_CUSTO,

                                               CUSTOMES02 = ML.PRECO_CUSTO,

                                               CUSTOMES01 = ML.PRECO_CUSTO,

                                               VQMES13 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -12, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0) + ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO inner join Natureza_operacao as np on np.Codigo_operacao = N.Codigo_operacao WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -12, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1 AND I.Codigo_operacao IN ('5102','5405','5402','5403','6102','6405','6401','6403') AND N.TIPO_NF = 1 AND N.status='AUTORIZADO' AND np.Saida = 1  and isnull(np.NF_devolucao,0) =0 ), 0),

                                               VQMES12 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -11, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0) + ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO inner join Natureza_operacao as np on np.Codigo_operacao = N.Codigo_operacao WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -11, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1 AND I.Codigo_operacao IN ('5102','5405','5402','5403','6102','6405','6401','6403') AND N.TIPO_NF = 1 AND N.status='AUTORIZADO' AND np.Saida = 1  and isnull(np.NF_devolucao,0) =0   ), 0),

                                               VQMES11 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -10, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0) + ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO inner join Natureza_operacao as np on np.Codigo_operacao = N.Codigo_operacao WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -10, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1 AND I.Codigo_operacao IN ('5102','5405','5402','5403','6102','6405','6401','6403') AND N.TIPO_NF = 1 AND N.status='AUTORIZADO' AND np.Saida = 1  and isnull(np.NF_devolucao,0) =0   ), 0),

                                               VQMES10 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -9, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0) + ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO inner join Natureza_operacao as np on np.Codigo_operacao = N.Codigo_operacao WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -9, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1 AND I.Codigo_operacao IN ('5102','5405','5402','5403','6102','6405','6401','6403') AND N.TIPO_NF = 1 AND N.status='AUTORIZADO' AND np.Saida = 1  and isnull(np.NF_devolucao,0) =0    ), 0),

                                               VQMES09 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -8, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0) + ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO inner join Natureza_operacao as np on np.Codigo_operacao = N.Codigo_operacao WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -8, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1 AND I.Codigo_operacao IN ('5102','5405','5402','5403','6102','6405','6401','6403') AND N.TIPO_NF = 1 AND N.status='AUTORIZADO' AND np.Saida = 1  and isnull(np.NF_devolucao,0) =0   ), 0),

                                               VQMES08 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -7, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0) + ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO inner join Natureza_operacao as np on np.Codigo_operacao = N.Codigo_operacao WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -7, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1 AND I.Codigo_operacao IN ('5102','5405','5402','5403','6102','6405','6401','6403') AND N.TIPO_NF = 1 AND N.status='AUTORIZADO' AND np.Saida = 1  and isnull(np.NF_devolucao,0) =0   ), 0),

                                               VQMES07 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -6, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0) + ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO inner join Natureza_operacao as np on np.Codigo_operacao = N.Codigo_operacao WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -6, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1 AND I.Codigo_operacao IN ('5102','5405','5402','5403','6102','6405','6401','6403') AND N.TIPO_NF = 1 AND N.status='AUTORIZADO' AND np.Saida = 1  and isnull(np.NF_devolucao,0) =0   ), 0),

                                               VQMES06 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -5, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0) + ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO inner join Natureza_operacao as np on np.Codigo_operacao = N.Codigo_operacao WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -5, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1 AND I.Codigo_operacao IN ('5102','5405','5402','5403','6102','6405','6401','6403') AND N.TIPO_NF = 1 AND N.status='AUTORIZADO' AND np.Saida = 1  and isnull(np.NF_devolucao,0) =0   ), 0),

                                               VQMES05 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -4, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0) + ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO inner join Natureza_operacao as np on np.Codigo_operacao = N.Codigo_operacao WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -4, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1 AND I.Codigo_operacao IN ('5102','5405','5402','5403','6102','6405','6401','6403') AND N.TIPO_NF = 1 AND N.status='AUTORIZADO' AND np.Saida = 1  and isnull(np.NF_devolucao,0) =0   ), 0),

                                               VQMES04 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -3, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0) + ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO inner join Natureza_operacao as np on np.Codigo_operacao = N.Codigo_operacao WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -3, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1 AND I.Codigo_operacao IN ('5102','5405','5402','5403','6102','6405','6401','6403') AND N.TIPO_NF = 1 AND N.status='AUTORIZADO' AND np.Saida = 1  and isnull(np.NF_devolucao,0) =0   ), 0),

                                               VQMES03 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -2, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0) + ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO inner join Natureza_operacao as np on np.Codigo_operacao = N.Codigo_operacao WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -2, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1 AND I.Codigo_operacao IN ('5102','5405','5402','5403','6102','6405','6401','6403') AND N.TIPO_NF = 1 AND N.status='AUTORIZADO' AND np.Saida = 1  and isnull(np.NF_devolucao,0) =0   ), 0),

                                               VQMES02 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -1, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0) + ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO inner join Natureza_operacao as np on np.Codigo_operacao = N.Codigo_operacao WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -1, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1 AND I.Codigo_operacao IN ('5102','5405','5402','5403','6102','6405','6401','6403') AND N.TIPO_NF = 1 AND N.status='AUTORIZADO' AND np.Saida = 1  and isnull(np.NF_devolucao,0) =0   ), 0),

                                               VQMES01 = ISNULL((SELECT SUM(S.QTDE) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, 0, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0) + ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO inner join Natureza_operacao as np on np.Codigo_operacao = N.Codigo_operacao WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, 0, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1 AND I.Codigo_operacao IN ('5102','5405','5402','5403','6102','6405','6401','6403') AND N.TIPO_NF = 1 AND N.status='AUTORIZADO' AND np.Saida = 1  and isnull(np.NF_devolucao,0) =0   ), 0),

                                               VVMES13 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -12, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),

                                               VVMES12 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -11, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),

                                               VVMES11 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -10, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),

                                               VVMES10 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -9, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),

                                               VVMES09 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -8, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),

                                               VVMES08 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -7, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),

                                               VVMES07 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -6, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),

                                               VVMES06 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -5, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),

                                               VVMES05 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -4, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),

                                               VVMES04 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -3, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),

                                               VVMES03 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -2, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),

                                               VVMES02 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -1, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),

                                               VVMES01 = ISNULL((SELECT SUM(S.VLR - ISNULL(DESCONTO, 0)) FROM SAIDA_ESTOQUE S (INDEX=IX_SAIDA_ESTOQUE_01) WHERE S.FILIAL = ML.FILIAL  AND S.PLU = M.PLU AND SUBSTRING(CONVERT(VARCHAR, S.DATA_MOVIMENTO, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, 0, GETDATE()), 102), 1, 7) AND S.DATA_CANCELAMENTO IS NULL), 0),

                                               EQMES13 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -12, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EQMES12 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -11, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EQMES11 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -10, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EQMES10 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -9, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EQMES09 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -8, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EQMES08 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -7, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EQMES07 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -6, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EQMES06 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -5, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EQMES05 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -4, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EQMES04 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -3, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EQMES03 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -2, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EQMES02 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -1, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EQMES01 = ISNULL((SELECT SUM(I.QTDE * I.EMBALAGEM) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, 0, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EVMES13 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -12, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EVMES12 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -11, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EVMES11 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -10, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EVMES10 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -9, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EVMES09 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -8, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EVMES08 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -7, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EVMES07 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -6, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EVMES06 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -5, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EVMES05 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -4, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EVMES04 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -3, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EVMES03 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -2, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EVMES02 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -1, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               EVMES01 = ISNULL((SELECT SUM(I.TOTAL + ISNULL(I.IVA, 0) + ISNULL(I.IPIV, 0)) FROM NF N (INDEX=IX_NF_01) INNER JOIN NF_ITEM I (INDEX=IX_NF_ITEM_01) ON N.FILIAL = I.FILIAL AND N.CLIENTE_FORNECEDOR = I.CLIENTE_FORNECEDOR AND N.CODIGO = I.CODIGO WHERE N.FILIAL = ML.FILIAL AND SUBSTRING(CONVERT(VARCHAR, N.DATA, 102), 1, 7) = SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, 0, GETDATE()), 102), 1, 7) AND I.PLU = M.PLU AND ISNULL(N.NF_CANC,0) <> 1), 0),

                                               FLAG = '',

                                               INICIO = '1900-01-01',

                                               FIM = '1900-01-01'

                               FROM

                                               MERCADORIA M

                                               INNER JOIN MERCADORIA_LOJA ML ON M.PLU = ML.PLU

                                               INNER JOIN FILIAL ON FILIAL.FILIAL = ML.FILIAL

                                               LEFT OUTER JOIN TRIBUTACAO T ON M.CODIGO_TRIBUTACAO = T.CODIGO_TRIBUTACAO

                               WHERE

                                               M.PLU <> '999999'

                END

                /*

                BEGIN

                               -- SELECIONA APENAS OS PRODUTOS QUE TIVERAM ENTRADAS

                               -- NOS ULTIMOS 13 MESES

                               SELECT DISTINCT NF.FILIAL, NF_ITEM.PLU INTO #PLUENTRADA FROM NF INNER JOIN NF_ITEM ON NF.FILIAL = NF_ITEM.FILIAL AND NF.CLIENTE_FORNECEDOR = NF_ITEM.CLIENTE_FORNECEDOR AND NF.CODIGO = NF_ITEM.CODIGO

                               WHERE SUBSTRING(CONVERT(VARCHAR, NF.DATA), 1, 7) >= SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -12, GETDATE()), 102), 1, 7)

 

                               IF (SELECT COUNT(*) FROM #PLUENTRADA) > 0

                               BEGIN

 

                                               UPDATE Acumulado_Geral SET INICIO = GETDATE()

 

                                               DECLARE curEntPLU CURSOR

                                                               FOR SELECT * FROM #PLUENTRADA

 

                                               OPEN curEntPLU

 

                                               FETCH NEXT FROM curEntPLU into @FILIAL, @PLU

 

                                               WHILE @@fetch_status = 0

                                                               BEGIN

                                                                               UPDATE Acumulado_Geral SET

                                                                                              CUSTOMES13 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -12, GETDATE()), 102), 1, 7)), PRECO_CUSTO),

                                                                                              CUSTOMES12 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -11, GETDATE()), 102), 1, 7)), PRECO_CUSTO),

                                                                                              CUSTOMES11 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -10, GETDATE()), 102), 1, 7)), PRECO_CUSTO),

                                                                                              CUSTOMES10 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -9, GETDATE()), 102), 1, 7)), PRECO_CUSTO),

                                                                                              CUSTOMES09 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -8, GETDATE()), 102), 1, 7)), PRECO_CUSTO),

                                                                                              CUSTOMES08 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -7, GETDATE()), 102), 1, 7)), PRECO_CUSTO),

                                                                                              CUSTOMES07 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -6, GETDATE()), 102), 1, 7)), PRECO_CUSTO),

                                                                                              CUSTOMES06 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -5, GETDATE()), 102), 1, 7)), PRECO_CUSTO),

                                                                                              CUSTOMES05 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -4, GETDATE()), 102), 1, 7)), PRECO_CUSTO),

                                                                                              CUSTOMES04 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -3, GETDATE()), 102), 1, 7)), PRECO_CUSTO),

                                                                                              CUSTOMES03 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -2, GETDATE()), 102), 1, 7)), PRECO_CUSTO),

                                                                                              CUSTOMES02 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, -1, GETDATE()), 102), 1, 7)), PRECO_CUSTO),

                                                                                              CUSTOMES01 = ISNULL(dbo.f_br_CUSTO_NA_DATA(FILIAL, PLU, SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, 0, GETDATE()), 102), 1, 7)), PRECO_CUSTO),

                                                                                              FLAG ='*'

                                                                               WHERE

                                                                                              Acumulado_Geral.FILIAL = @FILIAL

                                                                               AND

                                                                                              Acumulado_Geral.PLU = @PLU

 

                                                                               FETCH NEXT FROM curEntPLU into @FILIAL, @PLU

                                                               END

                                                               CLOSE curEntPLU

                                                               DEALLOCATE curEntPLUxPlu

                               END

                               UPDATE Acumulado_Geral SET FIM = GETDATE()

                END

                */

--            WHERE M.PLU = '1656'
go 



IF OBJECT_ID (N'nf_justificativa_edicao', N'U') IS NULL 
begin


 Create Table nf_justificativa_edicao(
  filial varchar(40),
  codigo_nota  varchar(20),
  usuario varchar(40),
  tipo_nf tinyint,
  data_alteracao datetime,
  justificativa nvarchar(max)
 )

end 
 
go 

	insert into Versoes_Atualizadas select 'Versão:1.243.782', getdate();
GO
